<?php
/**
 * APIBillingPeriodUsageOutTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it!
 *
 * OpenAPI spec version: 2.0.9
 * Contact: contact@namsor.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * APIBillingPeriodUsageOutTest Class Doc Comment
 *
 * @category    Class
 * @description APIBillingPeriodUsageOut
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class APIBillingPeriodUsageOutTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "APIBillingPeriodUsageOut"
     */
    public function testAPIBillingPeriodUsageOut()
    {
    }

    /**
     * Test attribute "api_key"
     */
    public function testPropertyApiKey()
    {
    }

    /**
     * Test attribute "subscription_started"
     */
    public function testPropertySubscriptionStarted()
    {
    }

    /**
     * Test attribute "period_started"
     */
    public function testPropertyPeriodStarted()
    {
    }

    /**
     * Test attribute "period_ended"
     */
    public function testPropertyPeriodEnded()
    {
    }

    /**
     * Test attribute "stripe_current_period_end"
     */
    public function testPropertyStripeCurrentPeriodEnd()
    {
    }

    /**
     * Test attribute "stripe_current_period_start"
     */
    public function testPropertyStripeCurrentPeriodStart()
    {
    }

    /**
     * Test attribute "billing_status"
     */
    public function testPropertyBillingStatus()
    {
    }

    /**
     * Test attribute "usage"
     */
    public function testPropertyUsage()
    {
    }

    /**
     * Test attribute "soft_limit"
     */
    public function testPropertySoftLimit()
    {
    }

    /**
     * Test attribute "hard_limit"
     */
    public function testPropertyHardLimit()
    {
    }
}
