<?php
/**
 * APIPlanSubscriptionOutTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 1000 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it!
 *
 * OpenAPI spec version: 2.0.2-beta
 * Contact: contact@namsor.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * APIPlanSubscriptionOutTest Class Doc Comment
 *
 * @category    Class
 * @description APIPlanSubscriptionOut
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class APIPlanSubscriptionOutTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "APIPlanSubscriptionOut"
     */
    public function testAPIPlanSubscriptionOut()
    {
    }

    /**
     * Test attribute "api_key"
     */
    public function testPropertyApiKey()
    {
    }

    /**
     * Test attribute "plan_started"
     */
    public function testPropertyPlanStarted()
    {
    }

    /**
     * Test attribute "prior_plan_started"
     */
    public function testPropertyPriorPlanStarted()
    {
    }

    /**
     * Test attribute "plan_ended"
     */
    public function testPropertyPlanEnded()
    {
    }

    /**
     * Test attribute "tax_rate"
     */
    public function testPropertyTaxRate()
    {
    }

    /**
     * Test attribute "plan_name"
     */
    public function testPropertyPlanName()
    {
    }

    /**
     * Test attribute "plan_base_fees_key"
     */
    public function testPropertyPlanBaseFeesKey()
    {
    }

    /**
     * Test attribute "plan_status"
     */
    public function testPropertyPlanStatus()
    {
    }

    /**
     * Test attribute "plan_quota"
     */
    public function testPropertyPlanQuota()
    {
    }

    /**
     * Test attribute "price_usd"
     */
    public function testPropertyPriceUsd()
    {
    }

    /**
     * Test attribute "price_overage_usd"
     */
    public function testPropertyPriceOverageUsd()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "price_overage"
     */
    public function testPropertyPriceOverage()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "currency_factor"
     */
    public function testPropertyCurrencyFactor()
    {
    }

    /**
     * Test attribute "stripe_customer_id"
     */
    public function testPropertyStripeCustomerId()
    {
    }

    /**
     * Test attribute "stripe_status"
     */
    public function testPropertyStripeStatus()
    {
    }

    /**
     * Test attribute "stripe_subscription"
     */
    public function testPropertyStripeSubscription()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }
}
