<?php
/**
 * SourceMetricsOutTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it!
 *
 * OpenAPI spec version: 2.0.9
 * Contact: contact@namsor.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * SourceMetricsOutTest Class Doc Comment
 *
 * @category    Class
 * @description Simple metrics on a classifier, for a given source
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SourceMetricsOutTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SourceMetricsOut"
     */
    public function testSourceMetricsOut()
    {
    }

    /**
     * Test attribute "classifier_name"
     */
    public function testPropertyClassifierName()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "ai_estimate_total"
     */
    public function testPropertyAiEstimateTotal()
    {
    }

    /**
     * Test attribute "ai_estimate_precision"
     */
    public function testPropertyAiEstimatePrecision()
    {
    }

    /**
     * Test attribute "ai_estimate_recall"
     */
    public function testPropertyAiEstimateRecall()
    {
    }

    /**
     * Test attribute "metric_time_stamp"
     */
    public function testPropertyMetricTimeStamp()
    {
    }

    /**
     * Test attribute "ai_start_time"
     */
    public function testPropertyAiStartTime()
    {
    }

    /**
     * Test attribute "ai_learn_total"
     */
    public function testPropertyAiLearnTotal()
    {
    }

    /**
     * Test attribute "snapshot_date"
     */
    public function testPropertySnapshotDate()
    {
    }
}
