<?php
/**
 * ChineseApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it!
 *
 * OpenAPI spec version: 2.0.7
 * Contact: contact@namsor.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ChineseApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChineseApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for chineseNameCandidates
     *
     * Identify Chinese name candidates, based on the romanized name ex. Wang Xiaoming.
     *
     */
    public function testChineseNameCandidates()
    {
    }

    /**
     * Test case for chineseNameCandidatesBatch
     *
     * Identify Chinese name candidates, based on the romanized name (firstName = chineseGivenName; lastName=chineseSurname), ex. Wang Xiaoming.
     *
     */
    public function testChineseNameCandidatesBatch()
    {
    }

    /**
     * Test case for chineseNameCandidatesGenderBatch
     *
     * Identify Chinese name candidates, based on the romanized name (firstName = chineseGivenName; lastName=chineseSurname) ex. Wang Xiaoming..
     *
     */
    public function testChineseNameCandidatesGenderBatch()
    {
    }

    /**
     * Test case for chineseNameGenderCandidates
     *
     * Identify Chinese name candidates, based on the romanized name ex. Wang Xiaoming - having a known gender ('male' or 'female').
     *
     */
    public function testChineseNameGenderCandidates()
    {
    }

    /**
     * Test case for chineseNameMatch
     *
     * Return a score for matching Chinese name ex. 王晓明 with a romanized name ex. Wang Xiaoming.
     *
     */
    public function testChineseNameMatch()
    {
    }

    /**
     * Test case for chineseNameMatchBatch
     *
     * Identify Chinese name candidates, based on the romanized name (firstName = chineseGivenName; lastName=chineseSurname), ex. Wang Xiaoming.
     *
     */
    public function testChineseNameMatchBatch()
    {
    }

    /**
     * Test case for genderChineseName
     *
     * Infer the likely gender of a Chinese full name ex. 王晓明.
     *
     */
    public function testGenderChineseName()
    {
    }

    /**
     * Test case for genderChineseNameBatch
     *
     * Infer the likely gender of up to 100 full names ex. 王晓明.
     *
     */
    public function testGenderChineseNameBatch()
    {
    }

    /**
     * Test case for genderChineseNamePinyin
     *
     * Infer the likely gender of a Chinese name in LATIN (Pinyin)..
     *
     */
    public function testGenderChineseNamePinyin()
    {
    }

    /**
     * Test case for genderChineseNamePinyinBatch
     *
     * Infer the likely gender of up to 100 Chinese names in LATIN (Pinyin)..
     *
     */
    public function testGenderChineseNamePinyinBatch()
    {
    }

    /**
     * Test case for parseChineseName
     *
     * Infer the likely first/last name structure of a name, ex. 王晓明 -> 王(surname) 晓明(given name).
     *
     */
    public function testParseChineseName()
    {
    }

    /**
     * Test case for parseChineseNameBatch
     *
     * Infer the likely first/last name structure of a name, ex. 王晓明 -> 王(surname) 晓明(given name)..
     *
     */
    public function testParseChineseNameBatch()
    {
    }

    /**
     * Test case for pinyinChineseName
     *
     * Romanize the Chinese name to Pinyin, ex. 王晓明 -> Wang (surname) Xiaoming (given name).
     *
     */
    public function testPinyinChineseName()
    {
    }

    /**
     * Test case for pinyinChineseNameBatch
     *
     * Romanize a list of Chinese name to Pinyin, ex. 王晓明 -> Wang (surname) Xiaoming (given name)..
     *
     */
    public function testPinyinChineseNameBatch()
    {
    }
}
